### ISSUE TITLE
using fisher's z-transform

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/sherlock-topic-model-paper#40]
In a number of notebooks, there are `_r2z` and `_z2r` functions defined, but never called, even when averaging correlation coefficients.  Was this intentional or do those calculations need updating?

**Comment by andrewheusser** [comment]
@paxtonfitzpatrick thanks for posting this, but I can't find what you are referring to.  i see `_r2z` and `_z2r` defined in `topic_model_analysis.ipynb`, but no averaging of correlation values. In that notebook, they were probably left in from previous code that I removed.  I can't find them in the other notebooks. can you post where specifically you saw these functions defined and where we've averaged correlation coefficients?

**Comment by paxtonfitzpatrick** [comment]
hey @andrewheusser,
it's kind of a tricky question of when to transform correlation coefficients because we're using correlation as an accuracy metric in a lot of instances.  However, r-values are averaged in:

- `main/wordle_analysis_and_fig.ipynb`, in the code for figure 4A
- same notebook, when computing the weighted average event vector, they're used as weights (but I think this is fine) 
- `main/eventseg_analysis.ipynb` (but this should be okay since they're treated as a ratio to find the optimal k value)
- `supp/movie_recall_correlation_features_impact.ipynb`
- `supp/parameter_search.ipynb`, in which movie-recall correlations are correlated with hand-annotated memory scores

there might've been a few other places I stumbled across it but they aren't popping out to me right. We should do a full check at some point soon.

**Comment by paxtonfitzpatrick** [comment]
This has been addressed in code revisions; closing
