### ISSUE TITLE
current issues with event segmentation code

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/sherlock-topic-model-paper#42]
I'm fixing these now but want to keep track of them somewhere:

- plots under *Plot the within and across correlation values as a function of k*  and *Plot the ratio of within/across ratio as a function of k* start at x=0, but should start at x=2
- normalizing video within/across correlation ratios to correct for non-monotonic behavior has typo.  Current: `t=list(map(lambda x: x[0]/(x[1]-min(m[1])), m))[1:]`.  Should be: `t=list(map(lambda x: x[0]/(x[1]-min([i[2] for i in m)), m))[1:]`
- wrong k-value is being subtracted for regularization parameter (should be `(i+2)/250` instead of `i/250` because of indexing of list `t`
- `maxk_video` is returning wrong number of events because of the way `t` is indexed.  Should be `maxk_video = np.argmax(t) + 2` instead of `maxk_video = np.argmax(t)`
- possibly extend normalization used with video k-optimization to recalls as well?
- the format of how `embeddings` is created and saved does not match how it's indexed when loading it into `trajectory_analysis_and_fig.ipynb`

**Comment by paxtonfitzpatrick** [comment]
after discussion, proceeding with the following edits:

- fixing a bug in the correction in the video k-optimization to deal with negative across-event correlations
- applying that same correction to the recall k-optimization for the following reasons:
  - want to establish the approach in a way that can account for recall trajectories with k-values that yield negative across-event correlations (like the video did)
  - applying the correction for negative correlations changes the optimal k-value for both the video and recalls.  Using it in one instance and not the other would improperly alter the proportion of video events recalled by participants
- resampling the recall trajectories to the timeseries of the video before performing event segmentation (as is currently reported in the paper) for the following reasons:
  - It's important to allow for the possibility that participants recalled more events than were presented (e.g., as with PLI's/XLI's in list-learning literature).  Resampling helps fix some issues with large potential k-values
  - Resampling helps deal with participants who use relatively few sentences to recall relatively large numbers of events (a small number of recall windows limits the range of k-values when not resampled).
  - the negative correlation correction step sometimes increases the number of recalled events.  Resampling mitigates this for unrealistically high numbers of recall events
  - it increases the relationship between our results and independently created, manually generated event recall scores (i.e., "reality")
  - it causes the distribution of event recall performance across participants by our method to better reflect that of the manually generated event recall scores

**Comment by jeremymanning** [comment]
Link to figure pdf: [[link](https://www.dropbox.com/s/d03er9nceaonxbx/sherlock-eventseg-versions.pdf)]

**Comment by paxtonfitzpatrick** [comment]
These have all either been addressed via bug fixes or are no longer relevant now that we've moved to using wasserstein distance for the K-optimization procedure.  Closing
