### ISSUE TITLE
requirement versions to pin

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/sherlock-topic-model-paper#43]
Just figured out the event segmentation analysis returns different results with `brainiak==0.7.1` and `brainiak=0.8.0` (seemingly due to changes [here](https://github.com/brainiak/brainiak/compare/39c8b09..b156fee#diff-5b228dc4d02f0beb4b0640b6cf45c896)).
There's also currently a [bug in matplotlib](https://github.com/mwaskom/seaborn/issues/1773) that causes issues with the correlation matrices, but can be fixed by pinning a `matplotlib` version.

With that in mind, we should pin these versions (imo) in the dockerfile:
- `numpy==1.17.0`
- `pandas==0.25.0`
- `hypertools==0.5.1`
- `matplotlib==3.1.0`
- `seaborn==0.9.0`
- `scikit-learn==0.19.1`
- `brainiak==0.7.1`
- `wordcloud==1.5.0`
- `pycircstat==0.0.2`
- (`quail` is already set to commit `25148aa506ed1d4133a0fbccafd0caf57867ef9`)

@andrewheusser can you add the versions of `nilearn` and `fastdtw` you used for the searchlight analyses/parameter search?
I'll add the rest in my next PR.

**Comment by andrewheusser** [comment]
`fastdtw==0.3.2`
`nilearn==0.4.2`

**Comment by paxtonfitzpatrick** [comment]
also pinned:
- `scipy==1.2.1` (minimum version with `wasserstein_distance` function)
- `xlrd==1.1.0` (minimum version required by pinned `pandas` version)

and updated `quail` to commit hash `71dd53c792dd915dc84879d8237e3582dd68b7a4` to include recent bug fixes
