### ISSUE TITLE
make Docker image more efficient

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/sherlock-topic-model-paper#72]
could cut size and build time of image shipped with paper for reproducing analyses by ~half with a few quick updates:
- wget anaconda -> miniconda
- install jupyter notebooks but not jupyterlab
- get rid of a bunch of apt packages that aren't needed
- combine some package install steps in Dockerfile to decrease image cache size
- optimize conda environment solve and pip installation order

**Comment by jeremymanning** [comment]
This sounds great if it's quick!

**Comment by paxtonfitzpatrick** [comment]
this was completed a while ago but never closed; closing now
