### ISSUE TITLE
proofread natbib-related changes

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/sherlock-topic-model-paper#79]
#### for example, line 102 (start of a paragraph) now reads:

 _<sup>23</sup>collected hand-annotated information about...._

#### where it used to read:

_Chen et al. (2017) collected hand-annotated information about..._

**Comment by paxtonfitzpatrick** [comment]
#### also line 221:
_according to both<sup>23</sup>'s hand-counted numbers..._

**Comment by jeremymanning** [comment]
i think i fixed all of these...but we do need to do a careful final proofread
